requires = ["tox>=4"]
env_list = ["lint", "type", "3.12"]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest"
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]
skip_missing_interperters = false

[env.lint]
description = "run linters"
skip_install = false
deps = ["black"]
commands = [["black", { replace = "posargs", default = ["."], extend = true} ]]

[env.type]
description = "run type checks"
deps = ["mypy"]
commands = [["mypy", { replace = "posargs", default = ["."], extend = true} ]]