requires = ["tox>=4"]
env_list = ["lint", "type", "format", "3.12"]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest"
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[env.lint]
description = "run linters"
skip_install = false
deps = [
    "ruff",
]
commands = [
    ["ruff", "check", { replace = "posargs", default = ["."], extend = true }],
]

[env.format]
description = "run code formatters"
skip_install = false
deps = [
    "black",
    "isort",
]
commands = [
    ["black", { replace = "posargs", default = ["."], extend = true }],
    ["isort", { replace = "posargs", default = ["."], extend = true }],
]

[env.type]
description = "run type checks"
deps = ["mypy"]
commands = [["mypy", { replace = "posargs", default = ["."], extend = true }]]