name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest, windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.12, 3.14]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff mypy pytest
      - name: Lint with ruff
        run: ruff .
      - name: Check formatting with black
        run: black --check .
      - name: Type check with mypy
        run: mypy .
      - name: Test with pytest
        run: pytest