name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        
    - name: Generate coverage report
      run: |
        pytest --cov=deepdreaming --cov-report=xml
        
    - name: Generate coverage badge
      uses: tj-actions/coverage-badge-py@v2
      with:
        output: coverage.svg
        
    - name: Commit coverage badge
      uses: EndBug/add-and-commit@v9
      with:
        add: 'coverage.svg'
        message: 'Update coverage badge'
        default_author: github_actions
